### ISSUE TITLE
parameters not showing correctly in inspector

### ISSUE THREAD

**Issue by LSka** [v7b1/sigmund_64bit-version#1]
Hello,
when I try and visualize or modify parameters from the Inspector, I see wrong values. Also, I can't modify them. I'm on Max 7.0.5, Mac OS X 10.9.5

**Comment by v7b1** [comment]
hi, thanks for your message. I can see what you mean, at least with some of the attributes - others seem to work fine. I haven't touched any of the attributes code yet, but i guess it is an issue with float vs doubles. i'll have a look, as soon as i find the time.

**Comment by v7b1** [comment]
actually, it was easy to fix. if you need a fixed compiled mac version you can redownload the sigmund~.zip from the latest release.
all the best,
volker

**Comment by LSka** [comment]
Thanks Volker, it works now!
Best,
Luca
