### ISSUE TITLE
error 126 when including in Standalone

### ISSUE THREAD

**Issue by jkaplan55** [v7b1/sigmund_64bit-version#3]
Hi,

I'd like to use this in a patch that I distribute as a standalone.  It works just fine in my patch.  And the standalone works just fine on my computer.  But when I send the standalone to my friend, he gets an error 126 in Max.  I believe Max throws this error when it can't find a necessary .dll.

Do you have any suggestions we might try?  Are there any other dependencies that need to be installed for this to work?  Or any thoughts on how to troubleshoot?  Thanks!

**Comment by v7b1** [comment]
Hello - I didn't do the windows compilation myself, so I can't really comment on that. But another user had an error 126 when trying to use [bonk~] and he was able to resolve it by installing VC library (2013).

**Comment by jkaplan55** [comment]
Thanks!  It tried installing the latest vc library and it had no effect.  But when I tried the 2013 version everything worked like a charm.

https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2013-vc-120

Ill make a note of this over on the forum.   Thanks for your work on this.  And thanks a ton for responding!
