### ISSUE TITLE
Arm64 release

### ISSUE THREAD

**Issue by rafalzalech** [v7b1/sigmund_64bit-version#4]
Dear v7b1! 

Do you plan to compile sigmund~  for the M1 Macs in the near future?

best regards,
Rafal

**Comment by v7b1** [comment]
It's already done - have a look here and see if it works for you [https://vboehm.net/maxobjects/sigmund_64bit-version.zip](https://vboehm.net/maxobjects/sigmund_64bit-version.zip)

**Comment by rafalzalech** [comment]
that worked, thanks!
