### ISSUE TITLE
Not working on Silicon?

### ISSUE THREAD

**Issue by hansteg** [v7b1/sigmund_64bit-version#5]
Hi,

so I had to get a new computer, and sigmund~ is not working on the new Mac M1 Pro: "could not load due to incorrect architecture". Is there any workaround?

Thanks, Hans

**Comment by v7b1** [comment]
I haven't found the time, yet, to prepare a proper release, but you can find an updated version here: [https://vboehm.net/downloads/](https://vboehm.net/downloads/)

**Comment by hansteg** [comment]
ah, that works, thanks! I see that you are also the author of vb.stretch~. Anything on the horizon for that one, or a suggestion for an alternative? Thanks a lot, Hans

**Comment by v7b1** [comment]
it's done already, but i need more time to finish up the whole vb-objects package, before i make everything available.
for your convenience i've just dropped the new external into the old zip on my download site (might need to refresh the page).

**Comment by hansteg** [comment]
Raaah, it works! Thanks a lot!!!!
